language: c

services:
    - redis-server

before_install:
    - sudo apt-get install -y libev-dev

install:
    - make env
    - make nginx

script:
    - make test
    - make qa
    - make cov
    - make e2e
